- name: 'GPT-SoVITS-2'
  type: 'GPT-SoVITS2'
  url: 'http://127.0.0.1:9880'
  config:
      # 这是基础的请求参数，可以设置一些东西，比如温度等
      # 具体参数看 api_v2.py 里的参数
      text_split_method: cut5
      batch_size: 1

  speakers:
      - name: '丛雨'
        # 底模路径，不设置则不切换
        gpt_weights: 'GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt'
        sovits_weights: 'SoVITS_weights_v2/Muramasa_e16_s6576.pth'
        # 参考音频是在你那个服务器部署上的路径，不是你本地的路径！！！
        ref_audio_path: 'audio/ムラサメ/mur001_062.ogg'
        aux_ref_audio_paths:
            - 'audio/ムラサメ/mur001_067.ogg'
            - 'audio/ムラサメ/mur003_012.ogg'
            - 'audio/ムラサメ/mur004_02.ogg'
        prompt_text: 'ほれ、吾輩の言った通りであろう？　なのにどうして、ご主人は……'
        prompt_lang: 'jp'
